# Generated by Django 2.1.2 on 2018-10-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
