# Generated by Django 2.1.2 on 2018-10-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181002_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='phone',
        ),
    ]
